import { open } from 'node:fs/promises';
import { isRecord } from '../lib/json';

export interface TranscriptStats {
  offset: number;
  input: number;
  output: number;
  branch?: string;
  /** Title chosen by the user. Always takes precedence. */
  customTitle?: string;
  /** Last title generated by Claude. */
  aiTitle?: string;
  /** The last prompt, as Claude Code records it (`last-prompt`). */
  lastPrompt?: string;
  /** The last compaction summary (`summary`). */
  summary?: string;
  /** The user's first message, failing everything else. */
  firstPrompt?: string;
  /**
   * Derived — the only field the display consumes — by the very rule the
   * Claude Code extension uses to name a tab and list sessions:
   * `customTitle ?? aiTitle ?? lastPrompt ?? summary ?? firstPrompt`.
   * An AI title is not generated for too short an exchange (« hello »),
   * and the tab then carries the prompt: the list must say the same thing.
   */
  title?: string;
}

/** What the tab shows of a prompt: its first line, whitespace folded, cut short. */
const PROMPT_TITLE_MAX = 80;
function promptTitle(v: unknown): string | undefined {
  const t = text(v);
  if (t === undefined) return undefined;
  const line = (t.split('\n').find((l) => l.trim().length > 0) ?? '').replace(/\s+/g, ' ').trim();
  if (line.length === 0) return undefined;
  return line.length > PROMPT_TITLE_MAX ? `${line.slice(0, PROMPT_TITLE_MAX - 1)}…` : line;
}

/** The text of a user record's message — a string, or the text blocks of an array; never a tool result. */
function userText(message: unknown): string | undefined {
  if (!isRecord(message)) return undefined;
  const content = message['content'];
  if (typeof content === 'string') return content;
  if (!Array.isArray(content)) return undefined;
  const parts: string[] = [];
  for (const block of content) {
    if (!isRecord(block)) continue;
    if (block['type'] === 'tool_result') return undefined;
    if (block['type'] === 'text' && typeof block['text'] === 'string') parts.push(block['text']);
  }
  return parts.length > 0 ? parts.join('\n') : undefined;
}

const EMPTY: TranscriptStats = { offset: 0, input: 0, output: 0 };

function num(v: unknown): number {
  return typeof v === 'number' && Number.isFinite(v) ? v : 0;
}

function text(v: unknown): string | undefined {
  if (typeof v !== 'string') return undefined;
  const t = v.trim();
  return t.length > 0 ? t : undefined;
}

/**
 * Reads a JSONL transcript from `from.offset`. The offset only advances up
 * to the last line break: a line still being written is reread on the next
 * pass rather than counted half-done.
 */
export async function readTranscript(path: string, from?: TranscriptStats): Promise<TranscriptStats> {
  const requested = from ?? EMPTY;
  let handle;
  try {
    handle = await open(path, 'r');
  } catch {
    return { ...requested };
  }

  try {
    const { size } = await handle.stat();
    if (size === requested.offset) return { ...requested };
    // The file is shorter than the stored offset: this is no longer the
    // transcript we were following (replaced, or a new session that
    // reused the same path). We forget the previous state and reread from
    // the start, so as not to keep stale totals indefinitely.
    const start = size < requested.offset ? EMPTY : requested;
    if (size <= start.offset) return { ...start, offset: Math.min(start.offset, size) };

    const length = size - start.offset;
    const buffer = Buffer.allocUnsafe(length);
    const { bytesRead } = await handle.read(buffer, 0, length, start.offset);
    // Bounded to bytesRead: beyond that, allocUnsafe wrote nothing — it's
    // uninitialized memory (a file truncated between stat() and read() is
    // the most plausible cause here), which must never be decoded.
    const chunk = buffer.toString('utf8', 0, bytesRead);

    const lastBreak = chunk.lastIndexOf('\n');
    if (lastBreak < 0) return { ...start };

    const stats: TranscriptStats = { ...start, offset: start.offset + Buffer.byteLength(chunk.slice(0, lastBreak + 1), 'utf8') };

    for (const line of chunk.slice(0, lastBreak).split('\n')) {
      if (line.length === 0) continue;
      let entry: unknown;
      try {
        entry = JSON.parse(line);
      } catch {
        continue;
      }
      if (!isRecord(entry)) continue;

      // « HEAD » is not a branch name but what Claude Code writes when
      // there isn't one: a folder outside a git repo, or a detached head.
      // Discarded here, at the boundary, rather than in the label — the
      // same rule as whitespace normalization (events/parse.ts): a value
      // that means nothing must never enter the state, or every display
      // has to remember to guard against it.
      const branch = entry['gitBranch'];
      if (typeof branch === 'string' && branch.length > 0 && branch !== 'HEAD') stats.branch = branch;

      const type = entry['type'];
      if (type === 'custom-title') {
        const t = text(entry['customTitle']);
        if (t !== undefined) stats.customTitle = t;
      } else if (type === 'ai-title') {
        const t = text(entry['aiTitle']);
        if (t !== undefined) stats.aiTitle = t;
      } else if (type === 'last-prompt') {
        const t = promptTitle(entry['lastPrompt']);
        if (t !== undefined) stats.lastPrompt = t;
      } else if (type === 'summary') {
        const t = promptTitle(entry['summary']);
        if (t !== undefined) stats.summary = t;
      } else if (type === 'user' && stats.firstPrompt === undefined && entry['isMeta'] !== true && entry['isSidechain'] !== true) {
        const t = promptTitle(userText(entry['message']));
        if (t !== undefined) stats.firstPrompt = t;
      }

      if (type !== 'assistant') continue;
      const message = entry['message'];
      if (!isRecord(message)) continue;
      const usage = message['usage'];
      if (!isRecord(usage)) continue;

      stats.input += num(usage['input_tokens']);
      stats.output += num(usage['output_tokens']);
    }

    stats.title = stats.customTitle ?? stats.aiTitle ?? stats.lastPrompt ?? stats.summary ?? stats.firstPrompt;
    return stats;
  } finally {
    await handle.close();
  }
}
